export const MOVIES_REQUESTED = 'MOVIES_REQUESTED';
export const MOVIES_LOADED = 'MOVIES_LOADED';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const FAV_MOVIES_REQUESTED = 'MOVIES_REQUESTED';
export const FAV_MOVIES_LOADED = 'MOVIES_LOADED';
export const FAV_MOVIES_ERROR = 'MOVIES_ERROR';
export const SET_SEARCH_BY_TITLE = 'SET_SEARCH_BY_TITLE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SORT_MOVIES = 'SORT_MOVIES';
export const SET_SEARCH_BY_ACTOR = 'SET_SEARCH_BY_ACTOR';
export const CLEAR_SEARCH_BY_ACTOR = 'CLEAR_SEARCH_BY_ACTOR';
export const AUTH = 'AUTH';


